services:
  _defaults:
    public: true

  json_rpc_params_sf_constraints_doc_sdk.tranformer:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\Infra\Transformer\ConstraintToParamsDocTransformer
    arguments:
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.type'
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.string'
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.min_max'
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.constraint_doc_payload'
