services:
  _defaults:
    public: true

  json_rpc_params_sf_constraints_doc.listener.jsonrpc_doc_server_created:
    class: Yoanm\SymfonyJsonRpcParamsSfConstraintsDoc\Listener\ServerDocCreatedListener
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_http_server_doc.server_doc_created'
        method: 'enhanceParamValidationErrorDoc'

  json_rpc_params_sf_constraints_doc.listener.jsonrpc_doc_method_created:
    class: Yoanm\SymfonyJsonRpcParamsSfConstraintsDoc\Listener\MethodDocCreatedListener
    arguments:
      - '@json_rpc_params_sf_constraints_doc_sdk.tranformer'
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_http_server_doc.method_doc_created'
        method: 'enhanceMethodDoc'
