services:
  _defaults:
    public: false

  json_rpc_params_sf_constraints_doc_sdk.helper.type:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\App\Helper\DocTypeHelper
    arguments:
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.constrain_doc_payload'
      - '@json_rpc_params_sf_constraints_doc_sdk.helper.type_guesser'

  json_rpc_params_sf_constraints_doc_sdk.helper.type_guesser:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\App\Helper\TypeGuesser

  json_rpc_params_sf_constraints_doc_sdk.helper.string:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\App\Helper\StringDocHelper

  json_rpc_params_sf_constraints_doc_sdk.helper.min_max:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\App\Helper\MinMaxHelper

  json_rpc_params_sf_constraints_doc_sdk.helper.constrain_doc_payload:
    class: Yoanm\JsonRpcParamsSymfonyConstraintDoc\App\Helper\ConstraintPayloadDocHelper
